- name: OpenShift Auto Recovery
  hosts: all
  sources:
    - ansible.eda.pg_listener:
        pg_port: 5432
  rules:
    - name: Application Down
      condition: true
      action:
        run_job_template:
          name: eda-test
          organization: Default
